### ISSUE TITLE
SQLAlchemy does not work with implicit DBname

### ISSUE THREAD

**Issue by mhaas-work** [dlopes7/autodynatrace#20]
Hello there!

If the DB URL is missing the `dbname` part, the database will now be recorded at all in the Dynatrace UI. Example URL: `postgresql://postgres:abcd@postgresql:5432/`
The current instrumentation expects that the URL contains a final part after the slash, which is interpreted as the DB name.

In this case, the `db_name` argument to `sdk.create_database_info` is the empty string and tracing will silently fail.

Changing the code as follows fixes the problem:

```
            db_name = conn.engine.url.database
            if not db_name:
                # Not all connection strings contain the database name.
                db_name = "default"
            db_host = conn.engine.url.host
```

I can submit a PR tomorrow; unless you beat me to it :)

Michael

**Comment by dlopes7** [comment]
Thanks for reporting!
