### ISSUE TITLE
autodynatrace is leaking calls on flask wrapper

### ISSUE THREAD

**Issue by elijahbal** [dlopes7/autodynatrace#21]
You call `wrapped()` in the finally clause, that is wrong because it is always called even when the `wrapped()` has been called and returned in the `try` clause.

See  this commit : [ac94f2946105f7f95cc1824db172eef31184c279](https://github.com/dlopes7/autodynatrace/commit/ac94f2946105f7f95cc1824db172eef31184c279).

The `return wrapped()` should be put into a generic catchall `except:` clause, not in the `finally:`, that is guaranteed to be executed whatever happens before in the block. Actually the first `return` clause is evaluated but not executed, because the `finally` clause preempt it.

```python
def f():
    try:
        return 1 + 2  # 1 + 2 is evaluated but the function does not return, the result is just stored for later
    finally:
        return 3 + 2  # return, the result of (1 + 2) is never reused
```
should become
```python
def f():
    try:
        return 1 + 2  # 1 + 2 is evaluated 
    except:
        return 3 + 2  # return here if exception is raised in (1 + 2) calculation
```

or 
```python
def f():
    res = None
    try:
        res = 1 + 2  # 1 + 2 is evaluated
    finally:
        return res if res is not None else 3 + 2  # return (3 + 2) if the previous call did not succeed
```

**Comment by dlopes7** [comment]
Thanks for this @elijahbal, I did not know about these details in the finally clause, very insightful!
