### ISSUE TITLE
'autodynatrace.wrappers.django' does not respect Composed

### ISSUE THREAD

**Issue by jamesjsanders** [dlopes7/autodynatrace#22]
Receive the error **_Attempted to pass non-string type to SDK function expecting a string._** when setting SQL query. 

### Python Code Causing Error: 
```
       with connections[settings.DB_ALIAS_MIRROR].cursor() as cursor:
            safe = SQL(query).format(**sql_params)
            cursor.execute(safe)
```

### Python Code Workaround:
```
       with connections[settings.DB_ALIAS_MIRROR].cursor() as cursor:
            safe = SQL(query).format(**sql_params).as_string(cursor.cursor)
            cursor.execute(safe)
```
### ArgumentError:
`argument 2: <class 'ValueError'>: Attempt to pass non-string type to SDK function expecting a string. Actual type: <class 'psycopg2.sql.Composed'>`

![image](https://user-images.githubusercontent.com/11224488/79249501-33c16b80-7e32-11ea-9ea3-00cb893c721f.png)

Server: **Linux 4.15.0-1063-aws #67-Ubuntu**
Autodynatrace Version: **1.0.36**
Service: **Django/UWSGI**
Django Version: **2.2.8**

**Comment by dlopes7** [comment]
Thanks for reporting, I will implement it shortly

**Comment by bartekbraktemporary** [comment]
[Sentry-1633047029](https://sentry.io/organizations/15five/issues/1633047029/) regressing. I will fix the python code but more investigation is needed.
