### ISSUE TITLE
Django & Celery fail to initialize the OneAgent 

### ISSUE THREAD

**Issue by avodaqstephan** [dlopes7/autodynatrace#25]
Hi, 

I tried to instrument our current Django, Celery stack with the most recent autodynatrace v1.0.38.
For that I: 

- Added autodynatrace to the requirements
- Imported autodynatrace to the settings.py like `import autodynatrace`
- Added `'autodynatrace.wrappers.django',` to the INSTALLED_APPS

The logs from kubernetes pods look like the following (same output for Django & Celery):

```
[2020-05-07 16:22:03 +0000] [84] [INFO] Starting gunicorn 19.9.0
[2020-05-07 16:22:03 +0000] [84] [DEBUG] Arbiter booted
[2020-05-07 16:22:03 +0000] [84] [INFO] Listening at: http://0.0.0.0:8000 (84)
[2020-05-07 16:22:03 +0000] [84] [INFO] Using worker: sync
[2020-05-07 16:22:03 +0000] [87] [INFO] Booting worker with pid: 87
[2020-05-07 16:22:03 +0000] [89] [INFO] Booting worker with pid: 89
[2020-05-07 16:22:03 +0000] [90] [INFO] Booting worker with pid: 90
[2020-05-07 16:22:03 +0000] [93] [INFO] Booting worker with pid: 93
[2020-05-07 16:22:03 +0000] [84] [DEBUG] 4 workers
2020-05-07 16:22:05,537: 87 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 1
2020-05-07 16:22:05,864: 93 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 1
2020-05-07 16:22:05,889: 89 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 1
2020-05-07 16:22:05,921: 90 WARNING autodynatrace - init: Could not initialize the OneAgent SDK, AgentState: 1
```

Did I miss a step?

We're running:
Django==3.0.5
celery==4.4.0

Kind regards, 
Stephan

**Comment by dlopes7** [comment]
Hello @avodaqstephan 

Thanks for reporting, gunicorn with Django 3 and celery 4 should work fine.
May I ask what is the docker base image being used (**FROM**)? I would like to attempt to reproduce the issue.

**Comment by avodaqstephan** [comment]
Hi @dlopes7 

we're using our own base image which I can't share. Is there a way to get more output from the agent SDK apart from the "Could not initialize the OneAgent SDK, AgentState: 1" message?

**Comment by dlopes7** [comment]
@avodaqstephan I don't need the image, only the first FROM. Unless you are creating the entire container from scratch.

You can attempt to set the oneagentsdk log level itself, as documented here: https://github.com/Dynatrace/OneAgent-SDK-for-Python#troubleshooting

State 1 means TEMPORARILY_INACTIVE, this usually means that the process was forked and the children cannot use the oneagent sdk libs, although there are other possible causes.

You can also try calling 

`autodynatrace.set_forkable()`

After importing, this makes it so that the SDK is only available for the child process, this assumes you are importing autodynatrace in the parent process. This should not be necessary for celery though.

**Comment by avodaqstephan** [comment]
@dlopes7 
The first **FROM** is a plain ubuntu:18.04.

I tried `autodynatrace.set_forkable()` in the `settings.py` but no luck.

I remembered that I used autodynatrace a while ago and tried version 1.0.18. Without changing any settings everything runs fine (Django + Celery).

Any ideas on how we can deep dive into the cause of the problem with newer releases? I'd would be open for a short call if you like.

**Comment by avodaqstephan** [comment]
I was able to get Django running with the newest version. We inherit some INSTALLED_APPS and I changed

`INSTALLED_APPS[0:0] = [
    'SomeApp.apps.SomeAppConfig',
]
`INSTALLED_APPS += [
    'autodynatrace.wrappers.django',
]`

to 
`
INSTALLED_APPS[0:0] = [
    'cary.apps.CaryConfig',
    'autodynatrace.wrappers.django',
]`

Still Celery refuses to work with 1.0.38 giving me the agent state: 1 error.

**Comment by dlopes7** [comment]
Shoot me an email at david.lopes@dynatrace.com so we can schedule a call to review the celery issue please. I am unable to replicate

**Comment by avodaqstephan** [comment]
@dlopes7 
I was partly wrong with my last comment. The part where you append `autodynatrace` to the INSTALLED_APPS seems to be important though. 

Celery is working. Initially there is a message in the logs with the `agentstate: 1` but actually if I run a task it gets monitored. So it was just a warning at the beginning but the instrumentation went through afterwards. 

A little proposal would be that even if the log level is set to `warning` at little message like `Instrumentation was successful` in the logs would be great.

**Comment by dlopes7** [comment]
Thanks @avodaqstephan, the celery message is confusing, the agent is disabled in the parent process, but enabled in the worker processes that do the tasks, that is why we get that "1" there
