### ISSUE TITLE
Django & Celery - Confusing service detection due to different 'app_name', 'context_root', 'host'

### ISSUE THREAD

**Issue by avodaqstephan** [dlopes7/autodynatrace#27]
Hi,

after instrumenting Django and Celery with this awesome plugin I discovered some difficulties in the service naming and detection in Kubernetes. I passed `DT_CUSTOM_PROPS` & `DT_TAGS` to create service and process group naming rules but my problem is now, that multiple services are getting created from just one Django process. 

Of course one process can have different services but in this case I'd like to have all of them merged or detected as just one service or atleast the 3 web services should be just one. Here is an example of my current detected services.

![image](https://user-images.githubusercontent.com/58725083/81809126-1d85f880-9521-11ea-864d-ea42aa12edd1.png)

They consist of 3 web services and 1 custom service. The web services are separated because the `webserver_name` or `application_id` are different. This probably comes from e.g. healthchecks which are coming from localhost vs external requests.

**Proposal:**

Because merging services in Dynatrace can only be done manually it would be nice to have the opportunity to overwrite the `app_name`, `application_id`, `context_root` via environment variables. Andreas Grabner came up with the following idea: 

host = os.environ.get("WAPPINFO_HOST", host)
name = os.environ.get("WAPPINFO_APPNAME", "Django ({})".format(app_name))
context_root = os.environ.get("WAPPINFO_CONTEXT_ROOT", "/")

**Celery:**

The same goes to Celery but here the different detected services do have different service types. They create 3 services, messaging service, listening service and celery itself.

Proposal: 

Would it make sense to bundle them into one service with 3 different endpoints instead? 

It is hard to describe the current situation just by words and one screenshot. If you like we can arrange a short call where I can show you the current situation in our environment.

Kind regards, 
Stephan

**Comment by dlopes7** [comment]
Hello @avodaqstephan 

For Django it makes perfect sense, we should be able to overwrite service names with environment variables. I will implement this later today, the variable names would have to follow the standard, so they will be:

- `AUTODYNATRACE_VIRTUAL_HOST`
- `AUTODYNATRACE_APPLICATION_ID`
- `AUTODYNATRACE_CONTEXT_ROOT`

For Celery it is a little more complicated, because it is a messaging service with different PIDs involved. Let me make some tests and see what we could do

**Comment by avodaqstephan** [comment]
Sound awesome @dlopes7 Thank you for the fast response!

**Comment by dlopes7** [comment]
@avodaqstephan 

The environment variables have been added.

For celery I believe we will have to stick with three components for now:

1.  The queue, in the screenshot the queue name happens to be the default queue name (celery)
2. The worker, the listener that receives the message.
3. The processing, the method in the worker that does the actual message processing

![Screenshot_20200513_190039](https://user-images.githubusercontent.com/10208081/81870650-ac5c3a80-954c-11ea-9c8a-d92d81e4ecdd.png)

If I remove any of these I can lose correlation, or I lie about response times

**Comment by avodaqstephan** [comment]
Hi @dlopes7 
that was quick! I immediately tried the new version and it seems to work like expected - almost. 
The 4 django services are now down to 2. One custom service and one web service. So far so good. But at the beginning for 1-3min there will be 2 web services. One of them did not pick up the environment variables from the beginning. 
After a few minutes the service goes offline and all requests are displayed within the other one. 

![image](https://user-images.githubusercontent.com/58725083/81905451-00a30100-95c5-11ea-9c5d-b9f286705c11.png)

I could imagine, that this more Dynatrace than autodynatrace related but I wanted to inform about this. There could be a problem, e.g if you start a test on a specific service right after the start and then the service vanishes and merges into another one.
